apiVersion: dashboard.grafana.app/v2beta1
kind: Dashboard
metadata:
  name: api-python-dashboard
  generation: 1
  creationTimestamp: '2025-11-04T22:59:26Z'
  labels: {}
  annotations: {}
spec:
  annotations:
    - kind: AnnotationQuery
      spec:
        builtIn: true
        enable: true
        hide: true
        iconColor: rgba(0, 211, 255, 1)
        name: Annotations & Alerts
        query:
          group: grafana
          kind: DataQuery
          spec: {}
          version: v0
  cursorSync: 'Off'
  editable: true
  elements:
    panel-1:
      kind: Panel
      spec:
        data:
          kind: QueryGroup
          spec:
            queries:
              - kind: PanelQuery
                spec:
                  hidden: false
                  query:
                    group: prometheus
                    kind: DataQuery
                    spec:
                      expr: process_cpu_seconds_total
                      legendFormat: CPU Total
                    version: v0
                  refId: A
            queryOptions: {}
            transformations: []
        description: ''
        id: 1
        links: []
        title: CPU Total do Processo (s)
        vizConfig:
          group: timeseries
          kind: VizConfig
          spec:
            fieldConfig:
              defaults:
                color:
                  mode: palette-classic
                custom:
                  axisBorderShow: false
                  axisCenteredZero: false
                  axisColorMode: text
                  axisLabel: ''
                  axisPlacement: auto
                  barAlignment: 0
                  barWidthFactor: 0.6
                  drawStyle: line
                  fillOpacity: 0
                  gradientMode: none
                  hideFrom:
                    legend: false
                    tooltip: false
                    viz: false
                  insertNulls: false
                  lineInterpolation: linear
                  lineWidth: 1
                  pointSize: 5
                  scaleDistribution:
                    type: linear
                  showPoints: auto
                  showValues: false
                  spanNulls: false
                  stacking:
                    group: A
                    mode: none
                  thresholdsStyle:
                    mode: 'off'
                thresholds:
                  mode: absolute
                  steps:
                    - color: green
                      value: 0
                    - color: red
                      value: 80
                unit: short
              overrides: []
            options:
              legend:
                calcs: []
                displayMode: list
                placement: bottom
                showLegend: true
              tooltip:
                hideZeros: false
                mode: single
                sort: none
          version: 12.3.0-18940657299.patch2
    panel-2:
      kind: Panel
      spec:
        data:
          kind: QueryGroup
          spec:
            queries:
              - kind: PanelQuery
                spec:
                  hidden: false
                  query:
                    group: prometheus
                    kind: DataQuery
                    spec:
                      expr: process_resident_memory_bytes
                      legendFormat: Memória Resident
                    version: v0
                  refId: A
              - kind: PanelQuery
                spec:
                  hidden: false
                  query:
                    group: prometheus
                    kind: DataQuery
                    spec:
                      expr: process_virtual_memory_bytes
                      legendFormat: Memória Virtual
                    version: v0
                  refId: B
            queryOptions: {}
            transformations: []
        description: ''
        id: 2
        links: []
        title: Uso de Memória do Processo
        vizConfig:
          group: timeseries
          kind: VizConfig
          spec:
            fieldConfig:
              defaults:
                color:
                  mode: palette-classic
                custom:
                  axisBorderShow: false
                  axisCenteredZero: false
                  axisColorMode: text
                  axisLabel: ''
                  axisPlacement: auto
                  barAlignment: 0
                  barWidthFactor: 0.6
                  drawStyle: line
                  fillOpacity: 0
                  gradientMode: none
                  hideFrom:
                    legend: false
                    tooltip: false
                    viz: false
                  insertNulls: false
                  lineInterpolation: linear
                  lineWidth: 1
                  pointSize: 5
                  scaleDistribution:
                    type: linear
                  showPoints: auto
                  showValues: false
                  spanNulls: false
                  stacking:
                    group: A
                    mode: none
                  thresholdsStyle:
                    mode: 'off'
                thresholds:
                  mode: absolute
                  steps:
                    - color: green
                      value: 0
                    - color: red
                      value: 80
                unit: bytes
              overrides: []
            options:
              legend:
                calcs: []
                displayMode: list
                placement: bottom
                showLegend: true
              tooltip:
                hideZeros: false
                mode: single
                sort: none
          version: 12.3.0-18940657299.patch2
    panel-3:
      kind: Panel
      spec:
        data:
          kind: QueryGroup
          spec:
            queries:
              - kind: PanelQuery
                spec:
                  hidden: false
                  query:
                    group: prometheus
                    kind: DataQuery
                    spec:
                      expr: python_gc_objects_collected_total
                      legendFormat: GC Objetos Coletados {{generation}}
                    version: v0
                  refId: A
            queryOptions: {}
            transformations: []
        description: ''
        id: 3
        links: []
        title: Objetos Coletados pelo GC
        vizConfig:
          group: stat
          kind: VizConfig
          spec:
            fieldConfig:
              defaults:
                thresholds:
                  mode: absolute
                  steps:
                    - color: green
                      value: 0
                    - color: red
                      value: 80
                unit: short
              overrides: []
            options:
              colorMode: value
              graphMode: area
              justifyMode: auto
              orientation: auto
              percentChangeColorMode: standard
              reduceOptions:
                calcs:
                  - lastNotNull
                fields: ''
                values: false
              showPercentChange: false
              textMode: auto
              wideLayout: true
          version: 12.3.0-18940657299.patch2
    panel-4:
      kind: Panel
      spec:
        data:
          kind: QueryGroup
          spec:
            queries:
              - kind: PanelQuery
                spec:
                  hidden: false
                  query:
                    group: prometheus
                    kind: DataQuery
                    spec:
                      expr: python_gc_objects_uncollectable_total
                      legendFormat: GC Objetos Não Coletáveis {{generation}}
                    version: v0
                  refId: A
            queryOptions: {}
            transformations: []
        description: ''
        id: 4
        links: []
        title: Objetos Não Coletáveis pelo GC
        vizConfig:
          group: stat
          kind: VizConfig
          spec:
            fieldConfig:
              defaults:
                thresholds:
                  mode: absolute
                  steps:
                    - color: green
                      value: 0
                    - color: red
                      value: 80
                unit: short
              overrides: []
            options:
              colorMode: value
              graphMode: area
              justifyMode: auto
              orientation: auto
              percentChangeColorMode: standard
              reduceOptions:
                calcs:
                  - lastNotNull
                fields: ''
                values: false
              showPercentChange: false
              textMode: auto
              wideLayout: true
          version: 12.3.0-18940657299.patch2
    panel-5:
      kind: Panel
      spec:
        data:
          kind: QueryGroup
          spec:
            queries:
              - kind: PanelQuery
                spec:
                  hidden: false
                  query:
                    group: prometheus
                    kind: DataQuery
                    spec:
                      expr: >-
                        http_request_duration_seconds_sum /
                        http_request_duration_seconds_count
                      legendFormat: Latência Média por Rota
                    version: v0
                  refId: A
            queryOptions: {}
            transformations: []
        description: ''
        id: 5
        links: []
        title: Latência Média das Requisições (s)
        vizConfig:
          group: timeseries
          kind: VizConfig
          spec:
            fieldConfig:
              defaults:
                color:
                  mode: palette-classic
                custom:
                  axisBorderShow: false
                  axisCenteredZero: false
                  axisColorMode: text
                  axisLabel: ''
                  axisPlacement: auto
                  barAlignment: 0
                  barWidthFactor: 0.6
                  drawStyle: line
                  fillOpacity: 0
                  gradientMode: none
                  hideFrom:
                    legend: false
                    tooltip: false
                    viz: false
                  insertNulls: false
                  lineInterpolation: linear
                  lineWidth: 1
                  pointSize: 5
                  scaleDistribution:
                    type: linear
                  showPoints: auto
                  showValues: false
                  spanNulls: false
                  stacking:
                    group: A
                    mode: none
                  thresholdsStyle:
                    mode: 'off'
                thresholds:
                  mode: absolute
                  steps:
                    - color: green
                      value: 0
                    - color: red
                      value: 80
                unit: s
              overrides: []
            options:
              legend:
                calcs: []
                displayMode: list
                placement: bottom
                showLegend: true
              tooltip:
                hideZeros: false
                mode: single
                sort: none
          version: 12.3.0-18940657299.patch2
    panel-6:
      kind: Panel
      spec:
        data:
          kind: QueryGroup
          spec:
            queries:
              - kind: PanelQuery
                spec:
                  hidden: false
                  query:
                    group: prometheus
                    kind: DataQuery
                    spec:
                      expr: sum by (handler, method, status) (http_requests_total)
                      legendFormat: '{{method}} {{handler}} {{status}}'
                    version: v0
                  refId: A
            queryOptions: {}
            transformations: []
        description: ''
        id: 6
        links: []
        title: Total de Requisições HTTP
        vizConfig:
          group: timeseries
          kind: VizConfig
          spec:
            fieldConfig:
              defaults:
                color:
                  mode: palette-classic
                custom:
                  axisBorderShow: false
                  axisCenteredZero: false
                  axisColorMode: text
                  axisLabel: ''
                  axisPlacement: auto
                  barAlignment: 0
                  barWidthFactor: 0.6
                  drawStyle: line
                  fillOpacity: 0
                  gradientMode: none
                  hideFrom:
                    legend: false
                    tooltip: false
                    viz: false
                  insertNulls: false
                  lineInterpolation: linear
                  lineWidth: 1
                  pointSize: 5
                  scaleDistribution:
                    type: linear
                  showPoints: auto
                  showValues: false
                  spanNulls: false
                  stacking:
                    group: A
                    mode: none
                  thresholdsStyle:
                    mode: 'off'
                thresholds:
                  mode: absolute
                  steps:
                    - color: green
                      value: 0
                    - color: red
                      value: 80
                unit: short
              overrides: []
            options:
              legend:
                calcs: []
                displayMode: list
                placement: bottom
                showLegend: true
              tooltip:
                hideZeros: false
                mode: single
                sort: none
          version: 12.3.0-18940657299.patch2
  layout:
    kind: GridLayout
    spec:
      items:
        - kind: GridLayoutItem
          spec:
            element:
              kind: ElementReference
              name: panel-1
            height: 8
            width: 24
            x: 0
            'y': 0
        - kind: GridLayoutItem
          spec:
            element:
              kind: ElementReference
              name: panel-2
            height: 8
            width: 24
            x: 0
            'y': 8
        - kind: GridLayoutItem
          spec:
            element:
              kind: ElementReference
              name: panel-3
            height: 4
            width: 12
            x: 0
            'y': 16
        - kind: GridLayoutItem
          spec:
            element:
              kind: ElementReference
              name: panel-4
            height: 4
            width: 12
            x: 12
            'y': 16
        - kind: GridLayoutItem
          spec:
            element:
              kind: ElementReference
              name: panel-5
            height: 8
            width: 24
            x: 0
            'y': 20
        - kind: GridLayoutItem
          spec:
            element:
              kind: ElementReference
              name: panel-6
            height: 8
            width: 24
            x: 0
            'y': 28
  links: []
  liveNow: false
  preload: false
  tags: []
  timeSettings:
    autoRefresh: 10s
    autoRefreshIntervals:
      - 5s
      - 10s
      - 30s
      - 1m
      - 5m
      - 15m
      - 30m
      - 1h
      - 2h
      - 1d
    fiscalYearStartMonth: 0
    from: now-6h
    hideTimepicker: false
    timezone: ''
    to: now
  title: Dashboard API Python
  variables: []
status: {}
